// <auto-generated />
namespace Projet_ASP.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class newTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(newTable));
        
        string IMigrationMetadata.Id
        {
            get { return "201502041855301_newTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
