// <auto-generated />
namespace Projet_ASP.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class matriculeEmploye : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(matriculeEmploye));
        
        string IMigrationMetadata.Id
        {
            get { return "201501300930358_matriculeEmploye"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
